name: agents
dependencies:
- python=3.11
- pip
- pip:
  # works for regular pip packages
  - openai==1.47.0
  - e2b-code-interpreter==0.0.10
  - python-dotenv==1.0.1
  - open-interpreter==0.3.12
  - langchain==0.2.16
  - langchain-openai==0.1.23
  - llm-sandbox